# Generated by Django 4.2.4 on 2023-10-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_noticias_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='descricao',
            field=models.TextField(verbose_name='Noticia'),
        ),
    ]
