# Generated by Django 4.2.4 on 2023-10-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], max_length=6, verbose_name='Prioridade')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lido', models.BooleanField(blank=True, default=False, verbose_name='Lido')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
